#include "coreconf_handlers.h"

#include <nanocbor/nanocbor.h>

#include <cstring>
#include <iostream>

// Import Coreconf headers (C library, needs extern "C" for C++ linkage)
extern "C" {
#include "coreconfManipulation.h"
#include "coreconfTypes.h"
#include "coreconf_config.h"  // Generated config header (includes instance header)
#include "serialization.h"
#include "sid_handlers.h"

// Forward declaration for generated handler registration function
// This will be generated by the autocoder from .sid files
void registerGeneratedHandlers(void);

// Forward declaration for generated GET handler
// This will be generated by the autocoder and can be overridden in impl file
CoreconfValueT *handleGetRequest(CoreconfValueT *coreconfModel);

// Forward declaration for generated PUT handler
// This will be generated by the autocoder and can be overridden in impl file
int handlePutRequest(CoreconfValueT **coreconfModel, CoreconfValueT *newValue, struct hashmap **clookupHashmap);
}

// TODO: For now we define some globals for testing. These will eventually move into a class once we can design this
// properly
CoreconfValueT *coreconfModel = NULL;
struct hashmap *clookupHashmap = NULL;
struct hashmap *keyMappingHashMap = NULL;

namespace coreconf {

void initialize_handlers(coap_context_t *ctx) {
    coap_resource_t *resource;

    // Create a root resource for CORECONF operations
    // In a real implementation, this would be /.well-known/coreconf or data model specific paths
    resource = coap_resource_init(coap_make_str_const("c"), 0);

    if (resource) {
        // Register handlers for different methods
        coap_register_handler(resource, COAP_REQUEST_GET, handle_get);
        coap_register_handler(resource, COAP_REQUEST_FETCH, handle_fetch);
        coap_register_handler(resource, COAP_REQUEST_PUT, handle_put);
        coap_register_handler(resource, COAP_REQUEST_IPATCH, handle_ipatch);

        // Add resource to context
        coap_add_resource(ctx, resource);
        std::cout << "CORECONF handlers registered successfully" << std::endl;
    } else {
        std::cerr << "Failed to create CORECONF resource" << std::endl;
    }

    // Do the initializations of the data structures needed for ccoreconf
    // Read cbor from coreconfModelCBORBuffer
    nanocbor_value_t decoder;
    nanocbor_decoder_init(&decoder, coreconfModelCBORBuffer, MAX_CORECONF_BUFFER_SIZE);

    coreconfModel = cborToCoreconfValue(&decoder, 0);
    printf("\nDeserialized Coreconf: \n");
    printCoreconf(coreconfModel);
    printf("\n");

    // Load key-mapping from keyMappingCBORBuffer
    nanocbor_value_t keyMappingDecoder;
    nanocbor_decoder_init(&keyMappingDecoder, keyMappingCBORBuffer, MAX_CORECONF_BUFFER_SIZE);
    keyMappingHashMap = cborToKeyMappingHashMap(&keyMappingDecoder);
    printf("Key Mapping: \n");
    printKeyMappingHashMap(keyMappingHashMap);
    printf("\n");

    // Build Chump Lookup hashmap for faster lookups
    clookupHashmap = hashmap_new(sizeof(CLookupT), 0, 0, 0, clookupHash, clookupCompare, clookupFree, NULL);

    // Build the CLookup hashmap from CoreconfModel
    buildCLookupHashmapFromCoreconf(coreconfModel, clookupHashmap, 0, 0);
    std::cout << "Chump lookup built: " << std::endl;
    printCLookupHashmap(clookupHashmap);
    std::cout << std::endl;

    // Initialize SID handler registry
    if (initializeSidHandlerRegistry() != 0) {
        std::cerr << "Failed to initialize SID handler registry" << std::endl;
    }

    // Register generated handlers
    registerGeneratedHandlers();

    // Print handler registry for debugging
    printHandlerRegistry();

    std::cout << "Initialized server" << std::endl;
}

void handle_get(coap_resource_t *resource, coap_session_t *session, const coap_pdu_t *request,
                const coap_string_t *query, coap_pdu_t *response) {
    std::cout << "=== GET Request Received ===" << std::endl;

    coap_show_pdu(LOG_WARNING, request);

    // Call the user-implemented GET handler (or default implementation)
    CoreconfValueT *responseValue = handleGetRequest(coreconfModel);

    if (responseValue == NULL) {
        std::cerr << "GET handler returned NULL" << std::endl;
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_INTERNAL_ERROR);
        return;
    }

    // Serialize the response value to CBOR
    uint8_t responseBuffer[MAX_CBOR_RESPONSE_PAYLOAD_SIZE] = {0};
    nanocbor_encoder_t encoder;
    nanocbor_encoder_init(&encoder, responseBuffer, MAX_CBOR_RESPONSE_PAYLOAD_SIZE);

    coreconfToCBOR(responseValue, &encoder);
    size_t responseSize = nanocbor_encoded_len(&encoder);

    // Print the response payload
    printf("GET Response Payload in CBOR Hex: ");
    for (size_t i = 0; i < responseSize; i++) {
        printf("%02x", responseBuffer[i]);
    }
    printf("\n");

    if (responseSize > 0) {
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_CONTENT);
        coap_add_data(response, responseSize, responseBuffer);
    } else {
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_INTERNAL_ERROR);
    }
}

void handle_put(coap_resource_t *resource, coap_session_t *session, const coap_pdu_t *request,
                const coap_string_t *query, coap_pdu_t *response) {
    std::cout << "=== PUT Request Received ===" << std::endl;

    coap_show_pdu(LOG_WARNING, request);

    size_t size;
    const uint8_t *data;

    // Get the payload from the request
    if (!coap_get_data(request, &size, &data)) {
        std::cout << "No payload in PUT request" << std::endl;
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_BAD_REQUEST);
        return;
    }

    std::cout << "PUT payload size: " << size << " bytes" << std::endl;

    // Parse the CBOR payload into a CoreconfValueT
    nanocbor_value_t decoder;
    nanocbor_decoder_init(&decoder, data, size);

    CoreconfValueT *newValue = cborToCoreconfValue(&decoder, 0);
    if (newValue == NULL) {
        std::cerr << "Failed to parse CBOR payload" << std::endl;
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_BAD_REQUEST);
        return;
    }

    printf("\nParsed new value from PUT request: \n");
    printCoreconf(newValue);
    printf("\n");

    // Call the user-implemented PUT handler for validation and replacement
    // The handler will validate, replace the model, and rebuild lookup structures
    int result = handlePutRequest(&coreconfModel, newValue, &clookupHashmap);

    if (result == 0) {
        // Success - newValue is now owned by coreconfModel, don't free it
        // Lookup hashmap has been rebuilt by handlePutRequest
        std::cout << "PUT succeeded - model replaced and lookup hashmap rebuilt" << std::endl;
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_CHANGED);
    } else {
        // Failure - free the newValue since it wasn't adopted
        std::cerr << "PUT failed with error code: " << result << std::endl;
        freeCoreconf(newValue, true);
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_BAD_REQUEST);
    }
}

void handle_fetch(coap_resource_t *resource, coap_session_t *session, const coap_pdu_t *request,
                  const coap_string_t *query, coap_pdu_t *response) {
    std::cout << "=== FETCH Request Received ===" << std::endl;

    coap_show_pdu(LOG_WARNING, request);

    // Get the payload from the request and convert to CoreconfValueT
    size_t size;
    const uint8_t *data;
    if (!coap_get_data(request, &size, &data)) {
        std::cout << "No payload in FETCH request" << std::endl;
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_BAD_REQUEST);
        return;
    }
    std::cout << "FETCH payload size: " << size << " bytes" << std::endl;

    nanocbor_value_t decoder;
    nanocbor_decoder_init(&decoder, data, size);

    // Initialize response
    CoreconfValueT *coreconfResponsePayload = createCoreconfArray();

    // Use the global key mapping (already loaded in initialize_handlers)
    // NOTE: Removed recreation of keyMappingHashMap here to avoid memory leak

    /* Fetch the payload (request SID and keys
        Payload will be in the format:
        [REQUESTED_SID_1, [REQUEST_SID2, REQUESTED_SID2_KEY1, REQUESTED_SID2_KEY2..]..]
        according to https://datatracker.ietf.org/doc/html/draft-ietf-core-comi-11#section-4.2.4
    */

    // TODO: we should try to remove this dependency on nanocbor from this level
    while (!nanocbor_at_end(&decoder)) {
        DynamicLongListT *requestKeys = createDynamicLongList();
        uint64_t requestSid = 0;
        CoreconfValueT *requestElement = cborToCoreconfValue(&decoder, 0);
        printf("\nDeserialized Coreconf: \n");
        printCoreconf(requestElement);
        printf("\n");

        // Extract request SID and keys based on element type
        if (isTypeUint(requestElement->type)) {
            // Query the coreconf model for an individual SID request (no keys)
            requestSid = getCoreconfValueAsUint64(requestElement);
        } else if (requestElement->type == CORECONF_ARRAY) {
            // The first element of the array is the request SID, the rest are SID keys
            CoreconfValueT *requestSidElement = &(requestElement->data.array_value->elements[0]);
            requestSid = getCoreconfValueAsUint64(requestSidElement);

            for (size_t j = 1; j < requestElement->data.array_value->size; j++) {
                CoreconfValueT *requestKeyElement = &(requestElement->data.array_value->elements[j]);
                uint64_t keyValue = getCoreconfValueAsUint64(requestKeyElement);

                addLong(requestKeys, keyValue);
            }
        } else {
            // Unknown type, cleanup and continue
            freeCoreconf(requestElement, true);
            freeDynamicLongList(requestKeys);
            continue;
        }

        // Common processing for both integer and array request types
        // Find the requirement for the SID
        PathNodeT *pathNodes = findRequirementForSID(requestSid, clookupHashmap, keyMappingHashMap);

        // NULL Check for pathNodes
        if (pathNodes == NULL) {
            printf("SID not found in the coreconf model\n");
            freeCoreconf(requestElement, true);
            // Move to the next requested SID
            nanocbor_skip(&decoder);
            continue;
        }

        // Print the PathNodeT
        printf("To reach your SID, the following SIDs  are traversed: \n");
        printPathNode(pathNodes);
        printf("---------\n");

        // Check if there's a registered handler for this SID
        CoreconfValueT *examinedValue = NULL;
        SidHandlerEntry *handler = lookupSidHandler(requestSid);

        if (handler != NULL && handler->readHandler != NULL) {
            printf("Found handler for SID %lu, calling custom read handler\n", requestSid);

            // Create context for handler
            SidHandlerContext ctx = {
                .sid = requestSid, .keys = requestKeys, .pathNode = pathNodes, .coreconfModel = coreconfModel};

            // Call the handler
            examinedValue = handler->readHandler(&ctx);

            if (examinedValue != NULL) {
                printf("Handler returned value successfully\n");
            } else {
                printf("Handler returned NULL, falling back to hashmap traversal\n");
            }
        }

        // NULL Check for examinedValue
        if (examinedValue == NULL) {
            printf("Couldn't find any results after the traversal\n");
            freePathNode(pathNodes);
            freeCoreconf(requestElement, true);
            // Move to the next requested SID
            continue;
        }

        printf("Coreconf subtree after traversal: \n");
        printCoreconf(examinedValue);
        printf("---------\n");
        addToCoreconfArray(coreconfResponsePayload, examinedValue);

        // Cleanup per-request temporary structures
        // NOTE: Don't free examinedValue - array owns it (transferred ownership)
        freePathNode(pathNodes);
        freeCoreconf(requestElement, true);
        freeDynamicLongList(requestKeys);
    }

    // Serialize the response payload
    uint8_t responsePayloadBuffer[MAX_CBOR_RESPONSE_PAYLOAD_SIZE] = {0};
    nanocbor_encoder_t encoder;
    nanocbor_encoder_init(&encoder, responsePayloadBuffer, MAX_CBOR_RESPONSE_PAYLOAD_SIZE);

    coreconfToCBOR(coreconfResponsePayload, &encoder);
    size_t responsePayloadSize = nanocbor_encoded_len(&encoder);

    // Print the response payload
    printf("Response Payload in CBOR Hex: ");
    for (size_t i = 0; i < responsePayloadSize; i++) {
        printf("%02x", responsePayloadBuffer[i]);
    }
    printf("\n");

    if (responsePayloadSize > 0) {
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_CONTENT);
        coap_add_data(response, responsePayloadSize, responsePayloadBuffer);
    } else {
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_INTERNAL_ERROR);
    }

    // Cleanup request-specific allocations
    freeCoreconf(coreconfResponsePayload, true);

    return;
}

void handle_ipatch(coap_resource_t *resource, coap_session_t *session, const coap_pdu_t *request,
                   const coap_string_t *query, coap_pdu_t *response) {
    std::cout << "=== iPATCH Request Received ===" << std::endl;

    size_t size;
    const uint8_t *data;

    // Get the payload from the request
    if (!coap_get_data(request, &size, &data)) {
        std::cout << "No payload in iPATCH request" << std::endl;
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_BAD_REQUEST);
        return;
    }

    std::cout << "iPATCH payload size: " << size << " bytes" << std::endl;

    nanocbor_value_t decoder;
    nanocbor_decoder_init(&decoder, data, size);

    bool allSucceeded = true;

    // Each element should be a map, but the key could be of the form
    // Payload format: Array of maps [{SID1: value1}, {SID2: value2}, ...]
    // Iterate through the array
    while (!nanocbor_at_end(&decoder)) {
        // [REQUESTED_SID_1, [REQUEST_SID2, REQUESTED_SID2_KEY1, REQUESTED_SID2_KEY2..]..]
        // so we need to handle that since an array is not hashable as a key and cannot be stored
        // TODO: Try to remove the knowledge of nanocbor from this level
        DynamicLongListT *requestKeys = createDynamicLongList();
        nanocbor_value_t map;
        int res;
        if (nanocbor_enter_map(&decoder, &map) < NANOCBOR_OK) {
            printf("Warning: Expected map in iPATCH request\n");
            freeDynamicLongList(requestKeys);
            nanocbor_skip(&decoder);
            continue;
        }

        // Extract request SID and keys from the map key
        CoreconfValueT *requestElement = cborToCoreconfValue(&map, 0);
        uint64_t requestSid = 0;

        // Extract request SID and keys based on element type
        if (requestElement->type == CORECONF_ARRAY) {
            // The first element of the array is the request SID, the rest are SID keys
            CoreconfValueT *requestSidElement = &(requestElement->data.array_value->elements[0]);
            requestSid = getCoreconfValueAsUint64(requestSidElement);

            for (size_t j = 1; j < requestElement->data.array_value->size; j++) {
                CoreconfValueT *requestKeyElement = &(requestElement->data.array_value->elements[j]);
                uint64_t keyValue = getCoreconfValueAsUint64(requestKeyElement);
                addLong(requestKeys, keyValue);
            }
        } else if (isTypeUint(requestElement->type)) {
            // Simple integer key (no additional keys)
            requestSid = getCoreconfValueAsUint64(requestElement);
        } else {
            // Unknown type, cleanup and continue
            freeCoreconf(requestElement, true);
            freeDynamicLongList(requestKeys);
            nanocbor_leave_container(&decoder, &map);
            continue;
        }

        // Get the value to write
        CoreconfValueT *requestValue = cborToCoreconfValue(&map, 0);

        printf("Processing write for SID %lu\n", requestSid);
        printf("New value: ");
        printCoreconf(requestValue);
        printf("\n");

        // Common processing for both integer and array key types
        // Find the requirement for the SID
        PathNodeT *pathNodes = findRequirementForSID(requestSid, clookupHashmap, keyMappingHashMap);
        if (pathNodes == NULL) {
            printf("SID %lu not found in the coreconf model\n", requestSid);
            freeCoreconf(requestElement, true);
            freeCoreconf(requestValue, true);
            nanocbor_leave_container(&decoder, &map);
            allSucceeded = false;
            continue;
        }

        printf("To reach SID %lu, the following path is traversed: \n", requestSid);
        printPathNode(pathNodes);
        printf("---------\n");

        // Check if there's a registered handler for this SID
        SidHandlerEntry *handler = lookupSidHandler(requestSid);
        int writeResult = -1;

        if (handler != NULL && handler->writeHandler != NULL) {
            printf("Found write handler for SID %lu, calling custom write handler\n", requestSid);

            // Create context for handler
            SidHandlerContext ctx = {
                .sid = requestSid, .keys = requestKeys, .pathNode = pathNodes, .coreconfModel = coreconfModel};

            // Call the write handler - pass the entire value structure
            writeResult = handler->writeHandler(&ctx, requestValue);

            if (writeResult == 0) {
                printf("Write handler succeeded for SID %lu\n", requestSid);
                // NOTE: Do NOT free requestValue here - the write handler has inserted it
                // into the coreconfModel, which now owns it
            } else {
                allSucceeded = false;
                printf("Write failed for SID %lu\n", requestSid);
                // Only free requestValue if write failed (not inserted into model)
                freeCoreconf(requestValue, true);
            }
        } else {
            // No handler found, free the value
            freeCoreconf(requestValue, true);
        }

        // Cleanup
        freePathNode(pathNodes);
        freeCoreconf(requestElement, true);
        freeDynamicLongList(requestKeys);

        nanocbor_leave_container(&decoder, &map);
    }

    // Set response code based on results
    if (allSucceeded) {
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_CHANGED);
        std::cout << "iPATCH completed successfully" << std::endl;
    } else {
        coap_pdu_set_code(response, COAP_RESPONSE_CODE_BAD_REQUEST);
        std::cerr << "iPATCH failed for one or more SIDs" << std::endl;
    }
}

size_t encode_cbor_response(std::vector<uint8_t> &buffer) {
    std::cout << "Encoding CBOR response..." << std::endl;

    // TODO: Use nanocbor to encode the response
    // Example nanocbor encoding structure:
    //
    // nanocbor_encoder_t encoder;
    // nanocbor_encoder_init(&encoder, buffer.data(), buffer.size());
    //
    // For GET: encode single value or subtree
    // For FETCH: encode CBOR map of SID -> value pairs
    // For iPATCH: optionally encode confirmation or error details

    // Placeholder: Create a simple CBOR map with dummy data
    buffer.resize(256);
    nanocbor_encoder_t encoder;
    nanocbor_encoder_init(&encoder, buffer.data(), buffer.size());

    // Create a simple map: {1: "placeholder"}
    nanocbor_fmt_map(&encoder, 1);
    nanocbor_fmt_uint(&encoder, 1);
    nanocbor_put_tstr(&encoder, "placeholder");

    size_t encoded_size = nanocbor_encoded_len(&encoder);
    buffer.resize(encoded_size);

    std::cout << "Encoded " << encoded_size << " bytes" << std::endl;
    return encoded_size;
}

void cleanup_handlers() {
    std::cout << "Cleaning up CORECONF resources..." << std::endl;

    // Free coreconf model
    if (coreconfModel) {
        freeCoreconf(coreconfModel, true);
        coreconfModel = NULL;
    }

    // Free clookup hashmap (includes automatic cleanup of CLookupT entries via clookupFree)
    if (clookupHashmap) {
        hashmap_free(clookupHashmap);
        clookupHashmap = NULL;
    }

    // Free key mapping hashmap (includes automatic cleanup of KeyMappingT entries via keyMappingFree)
    if (keyMappingHashMap) {
        hashmap_free(keyMappingHashMap);
        keyMappingHashMap = NULL;
    }

    // Free SID handler registry
    freeSidHandlerRegistry();

    std::cout << "CORECONF resources cleaned up" << std::endl;
}

}  // namespace coreconf
